### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by Shansky** [Optixal/i3blocks-crypto#3]
Line 17 - forgot to import sys first ;)

**Comment by Optixal** [comment]
My bad, I did not notice that when I merged #2. Thx for pointing that out :)

**Comment by Optixal** [comment]
Fixed with 44e4ea96b1c57392fa41178ecb164e8ba54e1a9f

**Comment by metadan** [comment]
Sorry that was my bad :)
