### ISSUE TITLE
Value in Euro

### ISSUE THREAD

**Issue by weppami** [Optixal/i3blocks-crypto#5]
Not really an issue, I dont really know cm api so.. is it possible to make a call returning the euro value for bitcoin ?
Nice work anyway !

Thanks a lot

**Comment by Optixal** [comment]
Unfortunately the API the crypto script queries only has the USD price of Bitcoin. You can add the following lines of code just after line 24 (`price = float(data['price_usd'])`) to retrieve the USD/EUR rate (https://exchangeratesapi.io), and then apply it to the price of Bitcoin:
```py
r2 = requests.get('https://api.exchangeratesapi.io/latest?base=USD')
currencyData = r2.json()
price *= currencyData['rates']['EUR']
